{{- if .Values.useAppConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chemsearch.configmapName" . }}
  labels:
    {{- include "chemsearch.labels" . | nindent 4 }}
data:
{{- range $file, $_ := .Values.appConfigs }}
  {{ $file }}: |
{{ $_.value | indent 4 }}
{{- end -}}
{{- end }}
