{{- range tuple "a" "b" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chemsearch.fullname" $ }}-{{ . }}
  labels:
    {{- include "chemsearch.labels" $ | nindent 4 }}
    rcsb.org/path: {{ . | quote }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chemsearch.selectorLabels" $ | nindent 4 }}
    rcsb.org/path: {{ . | quote }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chemsearch.fullname" . }}
  annotations:
    rcsb.org/path-operator-managed: "true"
  labels:
    {{- include "chemsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chemsearch.selectorLabels" . | nindent 4 }}
