name: Run CI/CD Workflow

on:
  push:
  workflow_dispatch:

jobs:
  run-workflow:
    name: "Run automated workflow"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-docker.yaml@master
    with:
      dockerfile_location: "Dockerfile"
      repo_url: "harbor.devops.k8s.rcsb.org"
      repo_project: "rcsb"
      docker_image_name: "rcsb-chemsearch"
      docker_build_context: "."
      mainline_branch: "k8s-staging"
