name: Run CI/CD Workflow

on:
  workflow_dispatch:
  #
  # Weekly rebuild, so that the image continues to pick up base-image and OS
  # security updates even when no application code has changed.
  schedule:
    # Time is based on UTC timezone
    #  ┌───────────── minute (0 - 59)
    #  │ ┌───────────── hour (0 - 23)
    #  │ │ ┌───────────── day of the month (1 - 31)
    #  │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #  │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #  │ │ │ │ │
    #  * * * * *
    - cron: "0 0 * * FRI"  # 0 UTC Friday
  #
  # Also run for new PRs and PR updates
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  #
  # And run when pushed to master
  push:
    branches:
      - master

jobs:
  run-workflow:
    name: "Run automated workflow"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-docker.yaml@master
    with:
      dockerfile_location: "Dockerfile"
      repo_url: "harbor.devops.k8s.rcsb.org"
      repo_project: "rcsb"
      docker_image_name: "rcsb-chemsearch"
      docker_build_context: "."
